

export const Routers = {
    adminRouters:{
        users:'/users',
        usersId:'/users/:userId',
        doctors:'/doctors',
        doctorsId:'/doctors/:doctorId',
        doctorId:'/doctor/:doctorId',
        verificationList:'/verification-list',
        doctorDetails:'/doctor-details/:doctorId',
        appoinments:'/appoinments',
        slotsAndAppoinments:'/getSlots/:doctorId',
        dashboardData:'/dashboard',
    },
    appoinmentRouters:{
        appoinments:'/appoinment',
        appoinmentCancel:'/appoinment/:appoinmentId',
        changeStatus:'/change-status/:appoinmentId',
    },
    authRouters:{
      login:'/login',
      signup:'/signup',
      verifyOtp:'/verify-otp',
      google:'/google',
      me:'/me',
      googleCallback:'/google/callback',
      logout:'/logout',
      resendOtp:'/resend-otp',
      sendOtp:'/send-otp',
      verifyEmail:'/verify-email',
      forgotPassword:'/forgot-password',
      refreshToken:'/refresh-token'
    },
    chatbotRouters:{
        chat:'/chat'
    },
    doctorRouters:{
        kycSubmit:'/kycSubmit/:doctorId',
        profile:'/profile/:id',
        reApply:'/reApply/:doctorId',
        appoinments:'/appoinments/:doctorId',
        dashboardData:'/dashboard/:doctorId'
    },
    notificationRouters:{
        notificationWithPatientId:'/notification/:patientId',
        notificationWithNotificationId:'/notification/:notificationId',
        readAllNotification:'/readAll-notification/:userId',
        deleteAllNotification:'/deleteAll-notification/:patientId',
    },
    patientRouters:{
        resendAppoinmentsWithPatientId:'/resend-appoinment/:patientId',
        profile:'/profile/:patientId',
        doctors:'/doctors',
        doctorId:'/doctor/:doctorId',
        slot:'/slots/:doctorId',
        specializations:'/specializations',
        checkout:'/checkout/:doctorId',
        relatedDoctors:'/related-doctors',
        changePassword:'/change-password/:patientId',
        appoinment:'/appoinment/:patientId'
    },
    paymentRouters:{
        order:'/order',
        verifyOrder:'/verifyOrder',
        walletPayment:'/wallet-payment'
    },
    slotRouters:{
        slots:'/slots',
        slotWithSlotId:'/slots/:doctorId'
    },
    walletRouters:{
        userWalletData:'/userWallet/:patientId',
        doctorWalletData:'/doctorWallet/:doctorId',
    },
    chatRouters:{
        getUserChat:'/user-chat/:patientId',
        sendMessage:'/send-message',
        getDoctorChat:'/doctor-chat/:doctorId',
        getDoctorMessage:'/doctor-messages/:chatId',
        getPatientMessage:'/patient-messages/:chatId',
        deleteMessage:'/delete-message/:messageId',
    },
    callLogRouters:{
        getCallData:'/call/:appoinmentId',
    },
    ratingRouters:{
        addRating:'/rating/:doctorId',
        findDoctorRating:'/rating/:doctorId'
    },
    prescriptionRouters:{
        create:'/prescription',
        download:'/download/:appoinmentId',
        getAppoinmentPrescription:'/prescription/:appoinmentId',
        updatePrescription:'/update-prescription/:appoinmentId',
    },
    contactRouters:{
        create:'/contact',
        getContacts:'/getContacts'
    },
    subscriptionRouters:{
        create:'/subscription',
        getAllSubscription:'/subscription',
        deleteSubscription:'/subscription/:subscriptionId'
    }
};
