export const Routers = {
    adminRouters:{
        users:'/users',
        usersId:'/users/:Id',
        doctors:'/doctors',
        doctorsId:'/doctors/:id',
        doctorId:'/doctor/:id',
        verificationList:'/verification-list',
        doctorDetails:'/doctor-details/:id',
        appoinments:'/appoinments'
    },
    appoinmentRouters:{
        appoinments:'/appoinment',
        appoinmentCancel:'/appoinment/:appoinmentId',
    },
    authRouters:{
      login:'/login',
      signup:'/signup',
      verifyOtp:'/verify-otp',
      google:'/google',
      me:'/me',
      googleCallback:'/google/callback',
      logout:'/logout',
      resendOtp:'/resend-otp',
      sendOtp:'/send-otp',
      verifyEmail:'/verify-email',
      forgotPassword:'/forgot-password',
      refreshToken:'/refresh-token'
    },
    chatbotRouters:{
        chat:'/chat'
    },
    doctorRouters:{
        kycSubmit:'/kycSubmit/:id',
        profile:'/profile/:id',
        reApply:'/reApply/:doctorId',
        appoinments:'/appoinments/:doctorId',
    },
    notificationRouters:{
        notificationWithPatientId:'/notification/:patientId',
        notificationWithNotificationId:'/notification/:notificationId'
    },
    patientRouters:{
        resendAppoinmentsWithPatientId:'/resend-appoinment/:patientId',
        profile:'/profile/:id',
        doctors:'/doctors',
        doctorId:'/doctor/:id',
        slot:'/slots/:id',
        specializations:'/specializations',
        checkout:'/checkout/:id',
        relatedDoctors:'/related-doctors',
        changePassword:'/change-password/:id',
        appoinment:'/appoinment/:patientId'
    },
    paymentRouters:{
        order:'/order',
        verifyOrder:'/verifyOrder'
    },
    slotRouters:{
        slots:'/slots',
        slotWithSlotId:'/slots/:id'
    }
};
